In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [21]:
data = pd.read_csv('CAR DETAILS.csv')

In [22]:
print(data.head())

                       name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner  


In [23]:
X = data[['year','selling_price','km_driven']]

In [24]:
X

year  selling_price  km_driven
0     2007          60000      70000
1     2007         135000      50000
2     2012         600000     100000
3     2017         250000      46000
4     2014         450000     141000
...    ...            ...        ...
4335  2014         409999      80000
4336  2014         409999      80000
4337  2009         110000      83000
4338  2016         865000      90000
4339  2016         225000      40000

[4340 rows x 3 columns]

In [25]:
y = data['owner']

In [15]:
y

0        First Owner
1        First Owner
2        First Owner
3        First Owner
4       Second Owner
            ...     
4335    Second Owner
4336    Second Owner
4337    Second Owner
4338     First Owner
4339     First Owner
Name: owner, Length: 4340, dtype: object

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
model = LogisticRegression(max_iter=200)

In [28]:
model.fit(X_train, y_train)

/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=200)

In [30]:
y_pred = model.predict(X_test)

In [31]:
accuracy = accuracy_score(y_test, y_pred)

In [32]:
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.66


In [33]:
print(classification_report(y_test, y_pred))

/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                      precision    recall  f1-score   support

         First Owner       0.69      0.94      0.80       570
Fourth & Above Owner       0.00      0.00      0.00         9
        Second Owner       0.38      0.15      0.22       228
      Test Drive Car       0.00      0.00      0.00         2
         Third Owner       0.67      0.03      0.06        59

            accuracy                           0.66       868
           macro avg       0.35      0.23      0.22       868
        weighted avg       0.60      0.66      0.59       868



In [34]:
conf_matrix = confusion_matrix(y_test, y_pred)

In [35]:
print(conf_matrix)

[[536   0  34   0   0]
 [  5   0   4   0   0]
 [192   0  35   0   1]
 [  2   0   0   0   0]
 [ 39   0  18   0   2]]
